### PR TITLE
[WIP]: Add Circleci configuration

### PR DESCRIPTION
**Pull request by andersy005**
The goal for having circleci in addition to Travis, is to use circleci for other tasks such as:

- docs testing
- code coverage,
- packaging (pip, conda)
- etc.

By diving tasks between travis and circleci, we can speed up the continuous integration process.

### CODE REVIEW

**Review by kmpaul — APPROVED** [review]
This looks great!  Thanks, @andersy005!

**Comment by andersy005** [comment]
@kmpaul, I forgot to mention that in order to preview the documentation, you can click on the Artifacts tab of CircleCI build page. You should see a drop-down list of artifacts that CircleCI has stored for us. Click on index.html and you should see a preview of the built documentation:

image

**Comment by kmpaul** [comment]
Is there a way to automatically publish the docs to a site, like readthedocs?

**Comment by andersy005** [comment]
Yes! https://readthedocs.org/ is a great option for this. Would you like us to work on this during our pair programming session next Monday? It would take ~ 30 minutes

**Comment by andersy005** [comment]
And if you are interested, we can also work on the conda packaging for conda-forge channel

**Comment by kmpaul** [comment]
Yes.  Let's add readthedocs and conda/pip packaging next Monday.

**Pull request merged**
